### ISSUE TITLE
don't write _influx.csv file with md5

### ISSUE THREAD

**Issue by sonejostudios** [Bugazelle/export-csv-to-influx#25]
Hi again @Bugazelle !
ExportCsvToInflux writes a _influx.csv with a md5 column for each processed file.
Now I have the following question: is it possible (i.e. with an arg) to NOT generate this _influx.csv file?

My CSVs are 100mb each, so this just would double the used space on the hard drive.

As workaroudn I could just delete them after injecting, but of course, it would be much better not to generate them ;)

Thank you in advance!

**Comment by Bugazelle** [comment]
Hello @sonejostudios 

Now the new version v0.1.23 support your feature.
Please add the `--force_insert_even_csv_no_update True` into your command

Hope it works on your side. 😄

If you encounter any bugs, you are very welcome to contact us to fix it.

Cheers ~~~

**Comment by sonejostudios** [comment]
Hi @Bugazelle ,

this works like a charm. Thank you so much!! :)

All the best
