### ISSUE TITLE
Cannot handle times before posix 1000000000

### ISSUE THREAD

**Issue by 7yl4r** [Bugazelle/export-csv-to-influx#32]
When processing 9-digit posix timestamps an error is thrown and the times are not inserted into influxdb.
I haven't tested it but I expect all timestamps less than 10 digits long will also fail.

I think the code expects a 10-digit timestamp and appends zeros to the end of the timestamp in an attempt to convert seconds to nanoseconds.

https://github.com/Bugazelle/export-csv-to-influx/blob/eb15d1c6b8932f659459666e60dc1fe9087266cb/src/ExportCsvToInflux/exporter_object.py#L431-L434

**Comment by Bugazelle** [comment]
Hello @7yl4r 

Really apologies for the dealy.
Year 2020 is a HELL Mode for me for both life and work.

I will take on this soon these days.

Thank you

**Comment by Bugazelle** [comment]
Hello @7yl4r :

Really appreciate for the pull requests.
You are right, it is a bug.

Thank you for the contribution!!
Now your code is in master branch now.

Have a nice day to you.

Cheers,
Bugazelle
