### ISSUE TITLE
force value to int or float fail messages are backwards

### ISSUE THREAD

**Issue by 7yl4r** [Bugazelle/export-csv-to-influx#36]
When failing to coerce a value to float the code reports that it failed to convert to int and vice versa.

**Comment by Bugazelle** [comment]
Hello @7yl4r 

Really apologies for the dealy.
Year 2020 is a HELL Mode for me for both life and work.

I will take on this soon these days.

Thank you

**Comment by Bugazelle** [comment]
Hello @7yl4r 

Yes, you are right.
Already fixed at: https://github.com/Bugazelle/export-csv-to-influx/commit/3b0d65894a76ad44b73b5d5d5e79afb37e6cfb9d

And I have invited you as the contributor.
Really appreciate for your help in advance

**Comment by Bugazelle** [comment]
Hello @7yl4r 

Released 0.1.25 to cover the fix: https://github.com/Bugazelle/export-csv-to-influx/releases/tag/v0.1.25
